<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-02-25 17:33
=======
# Generated by Django 5.0.6 on 2025-02-25 00:43
>>>>>>> f6b59873bf78c10d176c63a639ca75d6a1d1a0f6

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(default='default_number', max_length=50)),
                ('barcode', models.CharField(default='default_barcode', max_length=50)),
                ('qty', models.IntegerField(default='default_qty')),
                ('date', models.DateField(default='default_date')),
                ('vender', models.CharField(default='default_vender', max_length=10)),
                ('client', models.CharField(default='default_client', max_length=10)),
                ('category', models.CharField(default='default_category', max_length=2)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('date', models.DateField()),
                ('vender', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=2)),
>>>>>>> f6b59873bf78c10d176c63a639ca75d6a1d1a0f6
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
