# Generated by Django 5.1.6 on 2025-03-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='default_client', max_length=20),
        ),
    ]
