# Generated by Django 5.1.6 on 2025-07-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_current_status_product_noted_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='photo',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
