# Generated by Django 5.1.6 on 2025-07-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_photo_table_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to=''),
        ),
    ]
