# Generated by Django 5.1.6 on 2025-07-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_barcode_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_status',
            field=models.CharField(blank=True, default='0', max_length=1, null=True),
        ),
    ]
