# Generated by Django 5.1.6 on 2025-07-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ex_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
