# Generated by Django 5.1.6 on 2025-07-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_ex_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
